services:
  webserver:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
      - "8088:8088"
    volumes:
      - ./:/var/www/html
    restart: always
    environment:
      - PHP_MEMORY_LIMIT=256M
      - PHP_POST_MAX_SIZE=128M
      - PHP_UPLOAD_MAX_FILESIZE=128M
      - PHP_MAX_EXECUTION_TIME=120
      - PHP_MAX_INPUT_TIME=120
