services:
  webserver:
    build:
      context: .
      dockerfile: Dockerfile
    # Usamos puertos no estándar para evitar conflictos en Easypanel
    ports:
      - "8080:8080"  # Nginx
      - "8081:8081"  # OpenLiteSpeed HTTP
      - "8443:8443"  # OpenLiteSpeed HTTPS
      - "7088:7088"  # OpenLiteSpeed Admin
    volumes:
      - ./www:/var/www/html
    restart: always
    environment:
      - PHP_MEMORY_LIMIT=256M
      - PHP_POST_MAX_SIZE=128M
      - PHP_UPLOAD_MAX_FILESIZE=128M
      - PHP_MAX_EXECUTION_TIME=120
      - PHP_MAX_INPUT_TIME=120
